name: project_jantra
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^1.1.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  timeline_tile: ^2.0.0
 

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/jantra.png
    - assets/images/main_logo.png
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700